---
- name: setup db-server
  hosts: dbservers
  become: yes
  tasks:

    - name: install MySQL
      yum :
        name: mariadb-server
        state: present

    - name: install PY-MySQL
      yum :
        name: MySQL-python
        state: present

    - name: Start service MARIA-DB, if not running
      service:
        name: mariadb
        state: started


    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{db_name}}" 
        state: present

    - name: Add user "{dbuser{}}" to database
      mysql_user:
        name: "{{dbuser}}" 
        password: "{{db_passwd}}" 
        priv: '*.*:ALL'

    - name: reload service mariadb, in all cases
      systemd:
        name: mariadb
        state: restarted


