---

- name: setup webserver
  hosts: webservers
  become: yes
  tasks:
    
    - name: get python-apt
      apt:
        name: python-apt
        state: present  
      when: ansible_distribution == "Ubuntu"


    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
 
   

    - name: install the latest version of Apache on Centos 
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_distribution  == "CentOS"
     
    - name: Install apache service on Ubuntu avoid starting it immediately
      apt: name=apache2 state=present
      environment:
        RUNLEVLEL: 1  
      when: ansible_distribution == "Ubuntu"
 

    - name: Start service httpd, if not running 
      service:
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"
        
     

    - name: example copying file with owner and permissions
      copy:
        src: /home/ubuntu/ansibletmp/vprofile/exc1/website/webpage/
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644


    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "CentOS"



